# Generated by Django 5.2.4 on 2025-08-06 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMantenimiento',
            fields=[
                ('idEstadoMantenimiento', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoRecurso',
            fields=[
                ('idEstadoRecurso', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id_EstadoReserva', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_estado_reserva', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('idLab', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_lab', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_rol', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('idTipoRecurso', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_tipoRecurso', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('idRecurso', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_recurso', models.CharField(max_length=40)),
                ('descripcion', models.TextField(null=True)),
                ('memoria', models.IntegerField(null=True)),
                ('procesador', models.CharField(max_length=25, null=True)),
                ('almacenamiento', models.IntegerField(default=1, null=True)),
                ('sistema_operativo', models.CharField(max_length=10, null=True)),
                ('programas_instalados', models.CharField(max_length=30)),
                ('estado_recurso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistemaGestion.estadorecurso')),
                ('idLab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaGestion.laboratorio')),
                ('tipo_recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaGestion.tiporecurso')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('idMantenimiento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_mantenimiento', models.DateField()),
                ('descripcion', models.TextField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaGestion.estadomantenimiento')),
                ('idRecurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaGestion.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_reserva', models.DateField()),
                ('inicio_reserva', models.TimeField()),
                ('fin_reserva', models.TimeField()),
                ('estado_reserva', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaGestion.estadoreserva')),
                ('idLab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaGestion.laboratorio')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RolId', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='sistemaGestion.rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
