# Generated by Django 5.2.4 on 2025-07-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadomantenimiento',
            name='idEstadoMantenimiento',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='estadorecurso',
            name='idEstadoRecurso',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='idRol',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tiporecurso',
            name='idTipoRecurso',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
