# Generated by Django 5.2.4 on 2025-07-28 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestion', '0002_alter_estadomantenimiento_idestadomantenimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id_EstadoReserva', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_estado_reserva', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('inicio_reserva', models.DateTimeField()),
                ('fin_reserva', models.DateTimeField()),
                ('estado_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaGestion.estadoreserva')),
                ('idLab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaGestion.laboratorio')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
